// Integration into the existing worker. OpenNext auth/native/legacy APIs stay intact.
// @ts-expect-error Generated by the existing Osamosam release build.
import handler from '../.open-next/worker.js';
// @ts-expect-error Bundled from this repository's cloudflare/application.ts.
import {replacementRequest,loginReturn,cleanup as cleanupReplacement} from './replacement.mjs';
import {cleanup} from '../src/server/cloudflare/cleanup';
import type {CloudEnv} from '../src/server/cloudflare/runtime';
import {gatewayRequest} from '../src/server/cloudflare/gateway';
const worker = {
 async fetch(request:Request,env:CloudEnv,ctx:ExecutionContext){
  const forwarded=await gatewayRequest(request,env.OSAMOSAM_GATEWAY_SECRET);
  if(!forwarded)return new Response('Forbidden',{status:403,headers:{'Cache-Control':'no-store'}});
  const replacement=await replacementRequest(forwarded,env);
  if(replacement)return replacement;
  return loginReturn(forwarded,await handler.fetch(forwarded,env,ctx));
 },
 async scheduled(_:unknown,env:CloudEnv){await cleanupReplacement(env);await cleanup(env);},
};
export default worker;
