// Integration into the existing worker. OpenNext auth/native/legacy APIs stay intact.
// @ts-expect-error Generated by the existing Osamosam release build.
import handler from '../.open-next/worker.js';
// @ts-expect-error Bundled from this repository's cloudflare/application.ts.
import {replacementRequest,loginReturn,weddingBridgeRequest,weddingBridgeReturn,weddingOrigin,cleanup as cleanupReplacement} from './replacement.mjs';
import {cleanup} from '../src/server/cloudflare/cleanup';
import type {CloudEnv} from '../src/server/cloudflare/runtime';
import {gatewayRequest} from '../src/server/cloudflare/gateway';
const WEDDING_ORIGIN=weddingOrigin();
const worker = {
 async fetch(request:Request,env:CloudEnv&{WEDDING_GATEWAY_SECRET?:string},ctx:ExecutionContext){
  const forwarded=await gatewayRequest(request,env.OSAMOSAM_GATEWAY_SECRET);
  if(!forwarded){
   const wedding=await gatewayRequest(request,env.WEDDING_GATEWAY_SECRET);
   // The separate secret is accepted only for a fully signed Sites request.
   if(!wedding||!request.headers.has('x-osam-proxy-signature'))return new Response('Forbidden',{status:403,headers:{'Cache-Control':'no-store'}});
   const url=new URL(wedding.url),site=new URL(WEDDING_ORIGIN);site.pathname=url.pathname;site.search=url.search;
   const headers=new Headers(wedding.headers);headers.set('x-forwarded-host',site.host);headers.set('x-forwarded-proto','https');
   const incoming=new Request(site,wedding);const scoped=new Request(incoming,{headers});
   const page=await replacementRequest(scoped,{...env,NEXT_PUBLIC_SITE_URL:WEDDING_ORIGIN});if(page)return page;
   if(['GET','HEAD'].includes(scoped.method)&&/^\/(photos|samples)\/[a-z0-9-]+\.webp$/.test(site.pathname))return env.ASSETS.fetch(scoped);
   return new Response('Not found',{status:404});
  }
  const bridge=weddingBridgeRequest(forwarded);if(bridge)return bridge;
  const replacement=await replacementRequest(forwarded,env);
  if(replacement)return replacement;
  return weddingBridgeReturn(forwarded,loginReturn(forwarded,await handler.fetch(forwarded,env,ctx)));
 },
 async scheduled(_:unknown,env:CloudEnv){await cleanupReplacement(env);await cleanup(env);},
};
export default worker;
